Fix: Newer versions of FastAPI now require app as a middleware argument #188639880
* New versions of FastAPI require the app as a middleware argument.
* Fixes the exceptions:
TypeError: MoesifMiddleware.__init__() got multiple values for argument 'settings'
AttributeError: 'ExceptionMiddleware' object has no attribute 'get'
* Update LICENSE and cleanup/remove extra code from example